# Generated by Django 4.1.7 on 2023-02-27 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfDeclaration', models.CharField(max_length=1000, verbose_name='Имя декларации')),
                ('Income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Доход')),
                ('Expense', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Расход')),
                ('IncomeNoVAT', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Не облагаемый доход')),
                ('NonOperationIncome', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Внереализационные доходы')),
                ('Nalog', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Налог')),
                ('DayOfDeclare', models.DateTimeField(default=datetime.date.today, verbose_name='Дата подачи')),
                ('Comment', models.CharField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('Draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('LastNalog', models.DecimalField(decimal_places=2, default='100', max_digits=15, verbose_name='Налог за прошлый период')),
            ],
            options={
                'verbose_name': 'Декларация',
                'verbose_name_plural': 'Декларации',
            },
        ),
        migrations.CreateModel(
            name='MinistryOfTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfMinRole', models.CharField(max_length=1000, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('Surname', models.CharField(max_length=1000, verbose_name='Фамилия')),
                ('LastName', models.CharField(max_length=1000, verbose_name='Отчество')),
                ('Adres', models.CharField(max_length=1000, verbose_name='Адресс')),
                ('Email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('Phone', models.CharField(max_length=1000, verbose_name='Телефон')),
                ('WorkPhone', models.CharField(max_length=1000, verbose_name='Рабочий телефон')),
                ('WorkAdres', models.CharField(max_length=1000, verbose_name='Рабочий адресс')),
                ('NameOfOrganization', models.CharField(max_length=1000, verbose_name='Название организации')),
                ('UNP', models.PositiveIntegerField(default=0, verbose_name='УНП')),
            ],
            options={
                'verbose_name': 'Налогоплательщик',
                'verbose_name_plural': 'Налогоплательщики',
            },
        ),
        migrations.CreateModel(
            name='TypeOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfActivity', models.CharField(max_length=1000, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VATName', models.CharField(max_length=1000, verbose_name='Название')),
                ('VATPersent', models.PositiveSmallIntegerField(default=0, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Процент',
                'verbose_name_plural': 'Проценты',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('Name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('Question', models.CharField(max_length=5000, verbose_name='Вопрос')),
                ('Topic', models.CharField(default='', max_length=5000, verbose_name='Тема')),
                ('Declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.declaration', verbose_name='Декларация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questions', verbose_name='Написал')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='OfficePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('Surname', models.CharField(max_length=1000, verbose_name='Фамилия')),
                ('LastName', models.CharField(max_length=1000, verbose_name='Отчество')),
                ('Adres', models.CharField(max_length=1000, verbose_name='Адресс')),
                ('Email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('Phone', models.CharField(max_length=1000, verbose_name='Телефон')),
                ('WorkPhone', models.CharField(max_length=1000, verbose_name='Рабочий телефон')),
                ('Experience', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт работы')),
                ('Salary', models.PositiveSmallIntegerField(default=0, verbose_name='Зарплата')),
                ('Cabinet', models.PositiveSmallIntegerField(default=0, verbose_name='Кабинет')),
                ('JobTitle', models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='api.ministryoftaxes', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник налоговой службы',
                'verbose_name_plural': 'Работники налоговой службы',
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='Activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeofactivity', verbose_name='Вид деятельности'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='Procent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vat', verbose_name='Процент'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='TaxPayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxpayer', verbose_name='Налогоплательщик'),
        ),
        migrations.CreateModel(
            name='Debetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Debt', models.PositiveIntegerField(default=0, verbose_name='Долг')),
                ('DateOfPay', models.DateField(default=datetime.date.today, verbose_name='Дата выплаты')),
                ('Payer', models.ManyToManyField(default=18, to='api.taxpayer', verbose_name='Налогоплательщик')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
            },
        ),
    ]
